###
# Do not add configuration for things that are common to both bash and zsh
###

# Debug zsh startup. Uncomment to enable
# ZSHDEBUG=on
[ ${ZSHDEBUG} ] && zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

: ${ZSH_DISABLE_COMPFIX:=true}

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="powerlevel10k/powerlevel10k"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# P10K Customization overrides
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_NAMESPACE}<-->${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}@${P9K_KUBECONTEXT_CLUSTER}'
export POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
# export POWERLEVEL9K_TRANSIENT_PROMPT=off
export POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl'
# p10k-on-post-prompt() { p10k display '1'=hide '2/right/time'=show }
# p10k-on-pre-prompt()  { p10k display '1'=show '2/right/time'=hide }

# Automatically quote globs in URL and remote references
__remote_commands=(scp rsync)
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
zstyle -e :urlglobber url-other-schema '[[ $__remote_commands[(i)$words[1]] -le ${#__remote_commands} ]] && reply=("*") || reply=(http https ftp)'

# Disable zsh globbing (using wildcards in commands)
unsetopt nomatch

# Configure completion dirs
fpath=($ZSH_CUSTOM/plugins/zsh-completions/src $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)
fpath=($HOME/.dotfiles/completion $fpath)

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS=true
HYPHEN_INSENSITIVE=true

# Autosuggest Async                                                                      │
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Syntax highlight should be loaded before history-substring-search
plugins=(
    aliases
    autojump
    brew
    clipboard
    command-not-found
    common-aliases
    copypath
    copyfile
    dirhistory
    docker
    extract
    fzf-tab # Needs to be loaded before fast-syntax-highlighting  and auto-suggestions
    fast-syntax-highlighting
    fzf
    git
    gnu-utils
    golang
    history
    history-substring-search
    macos
    python
    ripgrep
    rsync
    sbt
    screen
    sudo
    systemd
    tmux
    vscode
    zsh-autosuggestions
    zsh-completions
    zsh-iterm-touchbar
    zsh-exa
)

source $ZSH/oh-my-zsh.sh

# Enable zsh plugins
source $ZSH_CUSTOM/plugins/autoupdate-oh-my-zsh-plugins/autoupdate.plugin.zsh
source $ZSH_CUSTOM/plugins/zsh-you-should-use/you-should-use.plugin.zsh
source $ZSH_CUSTOM/plugins/forgit/forgit.plugin.zsh

# Configure completion options
zstyle ':fzf-tab:complete:*:*' fzf-flags --height=80% --preview-window=right:wrap
zstyle ':fzf-tab:complete:*:options' fzf-preview
zstyle ':fzf-tab:complete:*:argument-1' fzf-preview
zstyle ':fzf-tab:*' switch-group ',' '.' # switch group using `,` and `.`
zstyle ':fzf-tab:complete:*:*' fzf-preview 'less ${(Q)realpath}'
export LESSOPEN='|$HOME/.dotfiles/bin/lessfilter %s'

zstyle ':completion:*:*:make:*' tag-order 'targets' # Only show targets on Makefile completion
zstyle ':completion:*:mill:*' sort false # Disable sort on mill completion
zstyle ':completion:*:git-checkout:*' sort false # Disable sort on git checkout
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} # set list-colors to enable filename colorizing
zstyle ':fzf-tab:complete:systemctl-*:*' fzf-preview 'SYSTEMD_COLORS=1 systemctl status $word'
zstyle ':fzf-tab:complete:ps:*' fzf-preview 'ps -p $word -o %cpu,%mem,rss'
zstyle ':fzf-tab:complete:(-command-|-parameter-|-brace-parameter-|export|unset|expand):*' fzf-preview 'echo ${(P)word}'

# Fuzzy matching of completions for when you mistype them:
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'

# Cache zsh completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# zmv
autoload -U zmv

# Disable zsh-autocompletion on paste
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# Key binds
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
# bindkey "^[[A" history-beginning-search-backward-end
# bindkey "^[[B" history-beginning-search-forward-end
# For iTerm2
# bindkey "^[^[[C" forward-word
# bindkey "^[^[[D" backward-word
# For Terminal
# bindkey "^[f" forward-word
# bindkey "^[b" backward-word

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
export HISTORY_SUBSTRING_SEARCH_FUZZY=true
setopt appendhistory
setopt SHARE_HISTORY

# Make pushd/popd silent
setopt PUSHDSILENT

# Initialize completions
autoload -Uz compinit
compinit

# Load additional shell rc common to zsh and bash
source $HOME/.dotfiles/shellconfig/shellrc.sh

# Debug zsh startup. Check variable on top.
[ ${ZSHDEBUG} ] && zprof
